<?php
/**
 * ${controllername}
 *
 * @copyright Copyright (c) ${commentsYear} ${CommentsCompanyName}
 * @author    ${commentsUserEmail}
 */
?>
<?php
/** @var \${Vendorname}\${Modulename}\Block\${Controllername} $block  */
// Add your template code here ...
?>
<h1 id="title"><?php echo __('${Modulename} ${Emailname}'); ?></h1>
<form id="${emailname}-request" class="form ${emailname}"
      action="<?php /* @escapeNotVerified */ echo $block->getFormAction(); ?>"
      id="${emailname}-form"
      method="post"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <div class="field name required">
            <label class="label" for="name"><span><?php /* @escapeNotVerified */ echo __('First Name') . ' ' . __('Last Name');?></span></label>
            <div class="control">
                <input name="name" id="name" title="<?php /* @escapeNotVerified */echo __('First Name') . ' ' . __('Last Name') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>







